✨ Move registrations list to /event
echo-webkom/echo-web pull request #311
Opened 2022-09-13 15:55 UTC by bakseter

### TL;DR: flyttet påmeldingslister til hvert enkelt arrangement, som bare er synlig om man er med i riktig undergruppe.

- Flyttet påmeldingslister til `/event`.
- Lagt til en kolonne `student_group_name` som sier hvem som arrangerer.
- Fjernet at det blir sendt mail når et nytt arrangement blir laget.
- Om man kjører lokalt, seeder vi database med masse testdata i stedet for å bruke et skript.
- Laget endepunkter for å hente/slette påmeldinger i frontend-API, som sender med Feide-email til backend, og da sjekker om denne emailen tilhører en studentgruppe. Samme som `/tilbakemeldinger`. Vi må legge inn alle mailene manuelt for at personer i studengruppene får tilgang.

## NB :rotating_light: ikke merge
Trengs fortsatt å oppdatere webhooks fra Sanity slik at man får inn arrangør for alle happenings. Slenger bare den her ut nå om noen vil se på den. Sikkert noe småtteri som må fikses.

2022-09-14 12:47 UTC, omfj requested changes
Har bare noen småting her. Brude kanskje få noen andre til også se på koden.

2022-09-14 12:47 UTC, omfj commented on frontend/src/lib/utils/first-upper.ts
> +const firstUpper = (str: string): string => str.charAt(0).toUpperCase() + str.slice(1);
Burde kanskje hete `capitalize`?

2022-09-14 12:47 UTC, omfj commented on backend/src/main/kotlin/no/uib/echo/plugins/Routing.kt
>          put("/feedback") {
Mangler sjekk på om den som oppdaterer tilbakemeldingen er med i webkom.

2022-09-14 12:51 UTC, omfj commented
Jeg synes vi burde ha noe tilsvarende `jwt("auth-webkom")`. Sånn at vi ikke trenger å sjekke email i selve funksjonen for endepunktet. Lett å glemme også er det en del boilerplate.

2022-09-21 11:27 UTC, boaanes approved these changes

2022-09-21 11:46 UTC, bakseter commented
@omfj enig i det, men da måtte jeg skrive denne:
```kotlin
jwt("auth-$undergruppe") {
    realm = "Verify user is in $undergruppe."
    verifier(jwkProvider, issuer) {
        acceptLeeway(3)
        withIssuer("https://auth.dataporten.no")
    }
    validate { jwtCredential ->
        // verifiser bruker her
    }
}
```

og denne:
```kotlin
authenticate("auth-$undergruppe") {
    getRegistrations(undergruppe)
}
```

manuelt for alle undergrupper. Og vi trenger uansett mailen til å sjekke undergruppen inne i selve endepunktet.
Prøvde å gjøre det dynamisk, men syntaksen til akkurat den configen er litt merkelig så fikk det ikke til.
Det kan evt. forbedres senere.

2022-09-21 11:48 UTC, bakseter commented on backend/src/main/kotlin/no/uib/echo/plugins/Routing.kt
>          }
den her er også litt støgg med `disableJwtAuth`, men det er pga. vi ikke har migrert tester til Ktor v2 enda. Det er en stor jobb så tar det på en workshop elns.

2022-09-21 11:57 UTC, omfj approved these changes
<img src="https://media0.giphy.com/media/fieipLNVGaGGY/giphy.gif"/>

2022-09-21 12:02 UTC, merged