🚧 Refactor and merge with master
echo-webkom/echo-web pull request #402
Opened 2022-10-09 15:12 UTC by omfj

Merget med master og skrev om litt. Tenker å legge til en melding som kommer på kalenderen når det ikke er noe som skjer en uke.

2022-10-10 17:46 UTC, omfj commented
@boaanes Eneste problemet er kanskje at vi laster ganske mye mer arrangementer enn det vi trenger. Hva tenker du?

2022-10-10 17:57 UTC, boaanes requested changes
Sånn overall synes jeg det ser bra ut! Men samtidig er det litt redundant å ha samme opplegg på fordisiden og `/arrangementer`... (ref. bruk av `EventOverview`) Vet ikke egt. hva som kunne vært nice å populere siden med.

Jeg digger ukeskalenderen da, og synes virkelig den bør ha en plass på nettsiden. Og ja - vi må finne en bedre måte å hente ut dataen på. Kanskje client side fetching med `useEffect` eller noe 🤔 

La også ved et par småkommentarer.

2022-10-10 17:57 UTC, boaanes commented on frontend/src/components/event-calendar.tsx
> +    first.getDate() === second.getDate();
Du kan bruke [isSameDay](https://date-fns.org/v2.29.3/docs/isSameDay) fra `date-fns` her

2022-10-10 17:57 UTC, boaanes commented on frontend/src/components/event-calendar.tsx
> +};
Denne har vi allerede i `src/lib/utils`

2022-10-10 17:57 UTC, boaanes commented on frontend/src/components/happening-calendar-box.tsx
> +            <a>
Hvorfor er `<a>` her egt? Accessibility?

2022-10-10 18:00 UTC, omfj commented on frontend/src/components/event-calendar.tsx
> +    first.getDate() === second.getDate();
word. den er egentlig resirkuelt fra når vi var i oslo 🤭

2022-10-10 20:16 UTC, omfj commented on frontend/src/components/happening-calendar-box.tsx
> +            <a>
haha aner ikke. gammel kode.

2022-10-10 20:23 UTC, omfj commented
Vi kan bruke `swr`!

Men enig i at denne siden egentlig ikke legger til så mye nytt og nyttig. Hvis noen har lyst til å lage en ny event preview for denne siden, så er det bare å kjøre på. 

Er ingen hast med å merge denne.

2022-10-10 22:07 UTC, boaanes commented
@omfj Ja swr er nice, se om du får det til å funke. Er egt. keen på å får merget så fort så mulig, vi bør ha short-lived branches og jobbe trunk based.

2022-10-10 22:08 UTC, omfj commented
@boaanes Merge og fikse bedre style senere da?

2022-10-10 22:11 UTC, boaanes commented
@omfj hva med å prøve å gjøre "Kommende / Tidligere" tabsene litt finere (kanskje ikke gjennomsiktig?). Også få på plass swr, så kan vi merge.

2022-10-13 20:32 UTC, boaanes commented
@omfj status?

2022-10-13 20:41 UTC, omfj commented
@boaanes skal prøve å bli ferdig med det imorgen.

2022-10-13 20:43 UTC, boaanes commented
Rått

2022-10-14 14:54 UTC, omfj commented
@boaanes Skal vi bare merge det? Jeg kommer ikke på noe god løsning på å redusere størrelsen på first load, og det er egentlig ingen grunn til å stresse det heller.

2022-10-14 14:54 UTC, omfj commented
Så lenge du er fornøyd med UI da, det kan jeg fortsatt jobbe med om du vil.

2022-10-16 09:55 UTC, boaanes commented
Jeg tenker merge @omfj

2022-10-16 09:56 UTC, boaanes approved these changes

2022-10-16 11:20 UTC, omfj commented
@boaanes Ikke endre knappene til "Forrige" og "Neste"?

2022-10-16 11:21 UTC, boaanes commented
gjorde det i siste commit @omfj

2022-10-16 11:21 UTC, omfj commented
@boaanes åja lol

2022-10-16 11:21 UTC, merged

2022-10-16 11:22 UTC, omfj commented
<img src="https://media1.giphy.com/media/KzDqC8LvVC4lshCcGK/giphy.gif"/>