♻️ Replace author with studentGroupName for Happening
echo-webkom/echo-web pull request #408
Opened 2022-10-10 14:44 UTC by bakseter

Unødvendig å ha begge to. Har kjørt et migrasjons-skript som setter `studentGroupName` til `author.name`. Venter med å unsette `author` til PR er merget så ikke prod krasjer.

2022-10-10 18:00 UTC, boaanes requested changes
LGTM, bortsett fra den ene kommentaren. Kanskje @omfj også vil se over?

2022-10-10 18:00 UTC, boaanes commented on frontend/src/lib/api/happening.ts
> +        literal('gnist'),
to gnist?

2022-10-10 19:51 UTC, omfj commented
Blir ikke dette veldig hardkodet da? Liksom hvis echo Mages har lyst til å ha et arrangement så må jeg inn å fikse decoderen og dropdownen i Sanity?

2022-10-10 19:59 UTC, omfj commented
Jeg synes vi burde prøve å "merge" "student_group_membership" i DB med det vi har i CMS (typ webhook). Da blir det vel lettere å styre hvem som kan ha tilgang på liste over påmeldte.

2022-10-10 21:09 UTC, bakseter commented
@omfj ja vet. Siden interessegrupper ikke har tilgang til Sanity, synes jeg ikke det er altfor mye styr at noen sender dem CSV med påmeldinger de få gangene i semesteret de har påmelding på siden. Jeg tror (?) vi sparer oss for mye unødvendig rot og kompleksitet i databasen ved å låse ned påmeldinger litt.

Jeg har også tenkt på sync mellom undergrupper på Sanity og undergrupper i databasen, men føler det kanskje blir mer av det slug-styret vi har hatt med happenings.

De undergruppene vi har i databasen er også i hovedsak for undergrupper som har påmeldinger, så vi trenger ikke ha alle der. Da kan vi bare skrive 'hovedstyret' og sende CSV.

2022-10-10 21:23 UTC, omfj commented
@bakseter Hvor mange webhooks har vi egentlig på Sanity? Jeg tror det blir lettere for oss å styre medlemskap i Sanity. Jeg og @TefiBoi skal jo lage et typ slikt system, da tenker jeg at det er mye lettere å prøve å rydde opp litt i Sanity, enn å lage et nytt system igjen for det.

2022-10-11 06:22 UTC, bakseter commented
@omfj vi har én igjen tror jeg. Men kom på nå at hvis det går via Sanity, så kan hvem som helst med Sanity-tilgang bare legge seg selv til i hvilken som helst undergruppe og få tilgang til alt. Vet ikke om det kan begrenses i Sanity?

2022-10-11 06:44 UTC, omfj commented
@bakseter det stemmer at alle som har tilgang til Sanity vil kunne endre medlemmer da, men jeg ser ikke på det som et problem. Jeg mener at de vi har på Sanity er "trusted". Sanity er flink med logger og versjon kontroll så skal være lett å fikse sånt.

2022-10-11 06:45 UTC, omfj commented
Mulig man kanskje kan begrense med roller, men så ikke ut som om at vi har tilgang til flere roller. Jeg kan sikkert sende mail til Sanity og høre hva de kan gjøre for oss med webhooks og roller.

2022-10-11 07:00 UTC, bakseter commented
@omfj sant, bare å kjøre på hvis dere tenker det er beste løsning.

Kan vel merge denne for å fjerne ‘author’ uansett, også bare endrer dere på decoders osv. når dere skal bruke ‘studentGroupName’.

2022-10-11 07:11 UTC, omfj commented
Merge i vei!

2022-10-11 08:16 UTC, bakseter commented
Trenger approve @omfj

2022-10-11 08:49 UTC, omfj approved these changes

2022-10-11 08:50 UTC, bakseter commented
og @boaanes

2022-10-11 08:59 UTC, boaanes approved these changes

2022-10-11 09:01 UTC, merged