✨ Popup feedback
echo-webkom/echo-web pull request #470
Opened 2022-10-26 16:34 UTC by omfj

2022-10-26 17:55 UTC, bakseter requested changes
Cypress test failer pga. popup er i veien, kanskje legge til en env-var som disable popup?

2022-10-26 17:55 UTC, bakseter commented on frontend/src/components/feedback-popup.tsx
> +                                    Engelsk hersjkj
:thinking:

2022-10-26 18:43 UTC, omfj commented
Ja tenkte det samme, men gjør det imorro @bakseter

2022-10-26 18:44 UTC, omfj commented on frontend/src/components/feedback-popup.tsx
> +                                    Engelsk hersjkj
Oj. Litt for agile

2022-10-27 10:56 UTC, bakseter approved these changes
<img src="https://media4.giphy.com/media/mi6DsSSNKDbUY/giphy-downsized-medium.gif"/>

2022-10-27 11:16 UTC, merged