Endre LanguageMenu
echo-webkom/echo-web pull request #501
Opened 2022-10-31 12:58 UTC by MathiasSJacobsen

Endre så det alltid vises to flagg i LanguageMenu.

Legge LanguageMenu I footeren.

Fjerne LanguageMenu fra article & Slug

2022-10-31 13:16 UTC, bakseter requested changes

2022-10-31 13:16 UTC, bakseter commented on frontend/src/components/footer.tsx
> +import LanguageMenu from './language-menu';
`'@components/language-menu'`

2022-10-31 13:25 UTC, boaanes requested changes
God innsats, har noen kommentarer. Og en annen ting - kan du finne på en måte å tydeligjøre hvilket språk som er valgt? Bakgrunnsfarge eller understrek eller noe...

2022-10-31 13:25 UTC, boaanes commented on frontend/src/components/language-menu.tsx
> +    type Flag = 'no' | 'en';
:thinking:

2022-10-31 13:25 UTC, boaanes commented on frontend/src/components/language-menu.tsx
> +            <Text>|</Text>
Bruk chakra sin `<Divider />`

2022-10-31 13:25 UTC, boaanes commented on frontend/src/components/language-menu.tsx
> +        <Flex justify={'center'}>
Bruk `justify="center"`, men også her tror jeg du egt. vil bruke `alignItems`.

```suggestion
        <Flex alignItems="center">
```

2022-10-31 13:25 UTC, MathiasSJacobsen commented on frontend/src/components/footer.tsx
> +import LanguageMenu from './language-menu';
Fikser det, fikk ikke linteren til å funke var i feil mappe

2022-10-31 13:52 UTC, MathiasSJacobsen commented on frontend/src/components/language-menu.tsx
> +        <Flex justify={'center'}>
Må ha begge for at den legger seg riktig med de andre

2022-10-31 13:52 UTC, MathiasSJacobsen commented on frontend/src/components/language-menu.tsx
> +    type Flag = 'no' | 'en';
🆔

2022-10-31 14:08 UTC, boaanes commented on frontend/src/components/language-menu.tsx
> +        setLanguage(lang);
bruh

2022-10-31 15:09 UTC, boaanes reviewed
@MathiasSJacobsen LGTM! Kan du rebase og squashe de commitsene som er litt overflødig? f.eks. `Bruh` og den med `mx`

2022-10-31 15:19 UTC, MathiasSJacobsen commented
Nå spør du meg om ting jeg ikke kan hehe

2022-11-07 14:33 UTC, MathiasSJacobsen commented
@bakseter ^

2022-11-07 14:42 UTC, bakseter approved these changes

2022-11-07 14:44 UTC, boaanes approved these changes

2022-11-08 16:23 UTC, merged