ny feature alert_echo om du opplever noe ugreit
echo-webkom/echo-web pull request #844
Opened 2023-02-02 12:36 UTC by Malintorset

Har laget en ny branch feature/alert_echo og fikser opp I feilene fra den gamle branchen

2023-02-02 14:48 UTC, bakseter commented
Du kan skrive `yarn format` i øverste del av repoet (altså i `echo-web` og ikke `echo-web/frontend`) for å fikse formatteringsfeil. Det er derfor noen av testene feiler.

2023-02-08 15:24 UTC, boaanes requested changes
Bra jobba, kun et par kommentarer :smile:

2023-02-08 15:24 UTC, boaanes commented on frontend/src/components/footer.tsx
> +                                             zIndex="100"
Hva gjør `zIndex` her?

2023-02-08 15:24 UTC, boaanes commented on frontend/src/components/footer.tsx
> +                                         </Text>
Den spacen kan fjernes

```suggestion
                                         <Text >
                                             Har du opplevd noe som ikke føltes helt greit på lesesalen eller på et echo
                                             arrangement?
                                         </Text>
```

2023-02-08 17:12 UTC, boaanes approved these changes
LGTM!

2023-02-08 19:34 UTC, bakseter requested changes
Mangler fortsatt koden for den nye siden? Kanskje den ikke kom med under `git add`?

2023-02-09 08:08 UTC, Malintorset commented
Prøvde å legge inn `{ name: 'Si ifra', href: '/om-echo/si-ifra' },` i `sidebar.tsx` og pusha, går det nå?

2023-02-09 08:13 UTC, Malintorset commented
Kommer fortsatt bare inn på 404 siden eksisterer ikke i previewen, fatter ikke hvorfor, hjelp 🥲

2023-02-09 08:23 UTC, Malintorset commented
funker nå 🤩

2023-02-09 08:25 UTC, bakseter approved these changes
Nydelig!

2023-02-09 08:26 UTC, merged