Feat/degregister from happening
echo-webkom/echo-web pull request #877
Opened 2023-02-08 21:42 UTC by omfj

2023-02-09 10:28 UTC, bakseter commented
FYI så kan man bruke `./scripts/test` for å kjøre Kotest lokalt :cowboy_hat_face:

2023-02-10 11:10 UTC, NixEngh commented
Har vi mye igjen å gjøre her anna enn å merge master inn? Det er aktive arrangement nå der det står at man må melde sæ av med mail og sånt, treng vi å gjøre nåkka med det?

2023-02-10 14:58 UTC, bakseter commented
> Har vi mye igjen å gjøre her anna enn å merge master inn? Det er aktive arrangement nå der det står at man må melde sæ av med mail og sånt, treng vi å gjøre nåkka med det?

1. Dere kan bare fjerne den gamle avmeldingslinken fra `frontend/src/components/happening-meta-info.tsx`, er bare noen linjer.
2. Slik det er nå, så er det ingen mulighet for arrangør å se hvem som har meldt seg av. Det er nok forvirrende dersom det bare forsvinner folk fra listen uten noe varsel. Jeg tror hvertfall Bedkom pleier å eksportere listen til CSV og holde styr på avmeldinger via Excel, siden da har de full fleksibilitet til å styre med avmeldinger, venteliste osv... Dette er jo et steg nærmere at man ikke trenger det lenger, men da må det være mulig å vite om folk har meldt seg av. En eller annen MVP løsning for å hvertfall se om en på lista har meldt seg av burde være på plass før det merges. Evt. høre med en eller flere av undergruppene hva de foretrekker.
3. Jeg får  `400 Bad Request` når jeg prøver å melde meg av på Vercel preview, funker det lokalt for dere?
4. Det er én backend-test som failer, den må fikses.

Lite tips til nr. 2 er i stedet for å lage en ny tabell `deregistration` så kan dere legge til f.eks. to nye nullable felter på `registration` som heter f.eks. `deregistration_date` og `reason`. Dersom en eller begge ikke er null, så har personen meldt seg av. Da kan dere lett lage en indikator i påmeldingslista i frontend som sier om personen er avmeldt eller ikke. Dette er nok lettest, men gjør hva dere synes er best.

2023-02-10 15:47 UTC, jkhammerseth commented
Kunne eg laga en knapp "getDeregisteredCSV" feks som returnera en csv fil med alle fra det arrangementet som e avmeldt? Sånn arrangør kan gå inn kortid som helst å få ut alle som e avregistrert

2023-02-11 16:31 UTC, omfj commented
@bakseter Kunne det være mulig å ha en type state i hver rad, sånn en for påmeldt, venteliste og avmeldt?

2023-02-11 16:38 UTC, bakseter commented
> Kunne eg laga en knapp "getDeregisteredCSV" feks som returnera en csv fil med alle fra det arrangementet som e avmeldt? Sånn arrangør kan gå inn kortid som helst å få ut alle som e avregistrert

Jeg mener det blir for knotete for arrangør, det burde helst vises tydelig i påmeldingslisten. Evt. en en separat liste i frontend (ikke CSV) som er lett tilgjengelig.

2023-02-11 16:44 UTC, bakseter commented
@omfj vi har allerede 'state' for påmeldt og venteliste, via feltet `waitlist: boolean` som er en del av `type Registration`. Det er derfor jeg foreslår å kombinere `Deregistration` og `Registration`, slik at det blir veldig lett for en rad å vite om den er påmeldt, på venteliste eller avmeldt.

F.eks.:

```typescript
interface Registration {
// ... andre felter her
deregistration_date: string | null;
reason: string | null;
}
```

```typescript
// inne i komponent:
{!registration.wailist && <Text>Har plass</Text>}
{registration.waitlist && <Text>På venteliste</Text>}
{registration.deregistration_date && <Text>Har meldt seg av</Text>}
```

Da trenger man bare å endre på typene til `Registration` i frontend (og evt. backend, spørs hvor mye dere vil endre på), og man kan bruke de samme endepunktene og funksjonene som allerede finnes. Man har allerede alle påmeldingene i påmeldingsliste-komponenten, så det trengs bare å slenge på noen ekstra felt her og der for å få det til.

2023-03-02 12:38 UTC, NixEngh commented
Det her må nok kombineres med prikkesystemet, siden folk må få prikka på en eller anna måte hvis de melde sæ sjøl av.

2023-03-02 14:57 UTC, bakseter requested changes

2023-03-02 14:57 UTC, bakseter commented on backend/src/main/resources/db/migration/V31_RegistrationStatus.sql
> +DROP COLUMN wait_list;
1. Denne må hete `V31__RegistrationStatus.sql`, altså med to understreker.
2. Mangler kolonnene `reason` og `deregistration_date`.

2023-03-02 14:57 UTC, bakseter commented on backend/src/main/kotlin/no/uib/echo/schema/Registration.kt
> +    val registrationStatus: Column<Status> = enumerationByName("registration_status", 16)
skal være `32` her

2023-03-02 14:57 UTC, bakseter commented on backend/src/main/kotlin/no/uib/echo/routes/RegistrationRoutes.kt
>                  }
Hva skjer her egt? Slettes svar uansett eller er det bare når man allerede er påmeldt? Og hva skjedde med sjekk for `registration.answers.isNotEmpty()`?

2023-03-02 14:57 UTC, bakseter commented on frontend/src/components/deregistration-button.tsx
> +                                </FormControl>
Ikke så farlig men trenger kanskje ikke bekrefte at man har fyllt inn riktig informasjon når det bare er én ting å fylle inn?

2023-03-02 14:57 UTC, bakseter commented on frontend/src/components/deregistration-button.tsx
> +                                        {isNorwegian ? 'Hvorfor melder du deg av?' : 'Why are you unregistering?'}
```suggestion
                                        {isNorwegian ? 'Hvorfor melder du deg av?' : 'Why are you deregistering?'}
```

2023-03-02 14:57 UTC, bakseter commented on frontend/src/pages/index.tsx
> +    if (isErrorMessage(registrationCountsResponse)) throw new Error(registrationCountsResponse.message);
Denne skal vekk

2023-03-22 18:18 UTC, closed without merging