creating a waitinglist system for event signup
echo-webkom/echo-web pull request #883
Opened 2023-02-09 14:03 UTC by Epirius

denne pull requesten er for å legge til et waitinglist system hvor man kan promotere en person fra en event kø ved å enten sende dem en epost eller direkte ved å klikke en knapp.

Hvordan dette fungerer:

1.

2023-02-09 16:33 UTC, omfj commented on frontend/src/pages/WaitingList/[uuid].tsx
> +            {!approved && !loading && !error && <div>du fikk dessverre ikke plassen</div>}
Gjør denne litt finere? Sånn typ kanskje et bilde eller gif over teksten som reflekterer om man fikk plass eller ikke. Også kan teksten kanskje være "Du fikk plass på {arr} den {dato}."

2023-02-09 16:33 UTC, omfj commented on frontend/src/pages/WaitingList/[uuid].tsx
> +            {!approved && !loading && !error && <div>du fikk dessverre ikke plassen</div>}
Kan også bruke `canvas-confetti` om man fikk plass.

2023-02-09 17:00 UTC, omfj requested changes
Har enda ikke prøvd å kjøre den lokalt, men dette er mine tanker etter å ha lest igjennom koden.

2023-02-09 17:00 UTC, omfj commented on frontend/src/components/registration-row.tsx
> +    const CheckIfCanPromote = async () => {
```suggestion
    const checkIfCanPromote = async () => {
```

camelCase og ikke PascalCase

2023-02-09 17:00 UTC, omfj commented on frontend/src/components/registration-row.tsx
> +        const response = await fetch(`${BACKEND_URL}/registration/promote/can_promote/${registration.slug}`, {
Burde flytte denne inn i en `WaitingListAPI`

2023-02-09 17:00 UTC, omfj commented on frontend/src/components/promote-button.tsx
> +        const responsePromote = await fetch(
Burde flytte denne inn i en `WaitingListAPI`

2023-02-09 17:00 UTC, omfj commented on frontend/src/components/promote-button.tsx
> +        <div>
```suggestion
        <>
```

Kan gjøres om til en React Fragment

2023-02-09 17:00 UTC, omfj commented on backend/src/main/kotlin/no/uib/echo/schema/WaitinglistUUID.kt
> +fun isPersonLegalToPromote(slug: String, userEmail: String): Boolean {
Denne returnerer bare `true`?

2023-02-09 17:00 UTC, omfj commented on backend/src/main/kotlin/no/uib/echo/routes/RegistrationRoutes.kt
> +                "Registration with email = $decodedParamEmail and slug = ${hap[Happening.slug]} deleted"
Denne endringen breaker testen. Så bare fiks testen til å forvente det du har her. #883 endrer også på denne funksjon, så alt etter som hvem som merger først, må sjekke at alt stemmer.

2023-02-09 17:00 UTC, omfj commented on backend/src/main/kotlin/no/uib/echo/routes/WaitinglistRoute.kt
> +                call.respond(HttpStatusCode.OK, "denied")
Skal vel være Unauthorized eller Forbidden?

2023-02-09 17:00 UTC, omfj commented on backend/src/main/kotlin/no/uib/echo/routes/WaitinglistRoute.kt
> +            call.respond(HttpStatusCode.Accepted, "approved")
Kan være 200 tror jeg. https://developer.mozilla.org/en-US/docs/web/http/status/202

2023-02-09 17:00 UTC, omfj commented on backend/src/main/kotlin/no/uib/echo/routes/WaitinglistRoute.kt
> +            println(adminEmail)
Kan fjernes.

2023-02-09 17:00 UTC, omfj commented on frontend/src/components/promote-button.tsx
> +        const responseEmail = await fetch(
Burde flytte denne inn i en `WaitingListAPI`

2023-02-09 17:00 UTC, omfj commented on frontend/src/pages/WaitingList/[uuid].tsx
> +            const responsePromote = await fetch(`${BACKEND_URL}/registration/promote/${uuid}`, {
Burde flytte denne inn i en `WaitingListAPI`

2023-02-09 17:02 UTC, omfj commented
Dere på også endre på `baselineVersion` til 29 i `DatabaseHandler.kt`

```kt
private val flyway: Flyway =
        Flyway.configure().baselineVersion("28").cleanDisabled(false).dataSource(dbUrlStr, dbUsername, dbPassword)
            .load()
````

2023-02-09 17:03 UTC, Epirius commented on backend/src/main/kotlin/no/uib/echo/schema/WaitinglistUUID.kt
> +fun isPersonLegalToPromote(slug: String, userEmail: String): Boolean {
ja den er der for integrering med prikke systemet etc

2023-02-09 17:08 UTC, Epirius commented on backend/src/main/kotlin/no/uib/echo/routes/WaitinglistRoute.kt
> +                call.respond(HttpStatusCode.OK, "denied")
jeg snakket med Bo om det i går. Forbidden er hvis du ikke har lov til å kalle endpointet. så selv om resultatet var "denied" så var http responsen ok.

vi kom fram til at jeg skulle bruke ok for dette og 202 accepted for godkjent.

2023-02-09 17:39 UTC, omfj commented on backend/src/main/kotlin/no/uib/echo/routes/WaitinglistRoute.kt
> +                call.respond(HttpStatusCode.OK, "denied")
Aha, da skjønner jeg.

2023-02-09 17:56 UTC, bakseter commented on backend/src/main/kotlin/no/uib/echo/routes/WaitinglistRoute.kt
> +                call.respond(HttpStatusCode.OK, "denied")
Tror det var litt misforståelse i går! Denne burde være 202 og den andre burde være 200. Vi bruker 202 som «request ok, men du fikk ikke plass» og 200 som «request ok, du fikk plass»

2023-02-14 15:57 UTC, Epirius commented
@omfj kan du sjekke om jeg skrev waitinglist migration riktig?
https://github.com/echo-webkom/echo-web/blob/047bb774ca637f99d9434e878384d9f8bbf7c0e1/backend/src/main/kotlin/no/uib/echo/schema/WaitinglistUUID.kt#L23-L33
https://github.com/echo-webkom/echo-web/blob/047bb774ca637f99d9434e878384d9f8bbf7c0e1/backend/src/main/resources/db/custom_sql.sql#L2-L23

2023-02-14 15:58 UTC, Epirius commented on frontend/src/pages/WaitingList/[uuid].tsx
> +            {!approved && !loading && !error && <div>du fikk dessverre ikke plassen</div>}
kjetil skal jobbe med dette, men vi kan merge i mellomtiden hvis alt annet er riktig.

2023-02-14 16:02 UTC, Epirius commented
migration er ikke riktig

2023-02-14 16:26 UTC, bakseter commented
@Epirius om du nullstiller database med `docker compose down` før du starter backend igjen, så vil du se query for å lage tabellen i loggen til Exposed når backend starter opp. Du kan bare kopiere den.

2023-02-14 16:37 UTC, bakseter commented
@Epirius btw det må også være to understreker i filnavnet, altså `V30__WaitinglistUUID.sql`.

2023-02-14 17:38 UTC, omfj commented on frontend/src/pages/WaitingList/[uuid].tsx
> +            {!approved && !loading && !error && <div>du fikk dessverre ikke plassen</div>}
Det er sant. Denne er ikke akkurat critical

2023-02-14 20:11 UTC, Epirius commented
@omfj 
<img src="https://media1.giphy.com/media/I1nwVpCaB4k36/giphy.gif"/>

2023-02-14 20:51 UTC, omfj requested changes

2023-02-14 20:51 UTC, omfj commented on backend/src/main/kotlin/no/uib/echo/schema/WaitinglistUUID.kt
> +    val lastNotified: Column<DateTime> = datetime("last_Notified").default(DateTime(0)) // default value is January 1st, 1970 (1970-01-01T01:00:00.000+01:00)
```suggestion
    val lastNotified: Column<DateTime> = datetime("last_notified").default(DateTime(0)) // default value is January 1st, 1970 (1970-01-01T01:00:00.000+01:00)
```

2023-02-14 20:51 UTC, omfj commented on backend/src/main/resources/db/migration/V30__WaitinglistUUID.sql
> +    "last_Notified" TIMESTAMP DEFAULT '1970-01-01 00:00:00.000000' NOT NULL,
```suggestion
    "last_notified" TIMESTAMP DEFAULT '1970-01-01 00:00:00.000000' NOT NULL,
```

2023-02-14 20:51 UTC, omfj commented on backend/src/main/resources/db/migration/V30__WaitinglistUUID.sql
> +ALTER TABLE waiting_list_uuid ADD CONSTRAINT waiting_list_uuid_user_email_happening_slug_unique UNIQUE (user_email, happening_slug)
Kan ikke dette gjøres mens tabellen blir laget?

2023-02-14 21:33 UTC, bakseter commented on backend/src/main/resources/db/migration/V30__WaitinglistUUID.sql
> +ALTER TABLE waiting_list_uuid ADD CONSTRAINT waiting_list_uuid_user_email_happening_slug_unique UNIQUE (user_email, happening_slug)
Sikkert, men har ikke noe å si egt. Den skal bare kjøres én gang. Det er sånn Exposed gjør det.

2023-02-14 21:34 UTC, bakseter commented
Har dere testet at det funker med de nyeste endringene? Jeg fikk ikke opp knappen for å promote i sted, fulgte oppskriften deres.

2023-02-14 21:43 UTC, Epirius commented
@bakseter den fungerer for meg, vi kan se på det i morgen.

2023-02-14 21:46 UTC, bakseter requested changes
Har bare littttegranne småtteri, ellers nice!

2023-02-14 21:46 UTC, bakseter commented on frontend/src/components/registration-row.tsx
> +                        {canPromote ? <PromoteButton registration={registration} /> : 'ja'}
```suggestion
                        {canPromote ? <PromoteButton registration={registration} /> : 'Ja'}
```

2023-02-14 21:46 UTC, bakseter commented on frontend/src/lib/api/waitinglist.ts
> +    checkIfCanPromote: async (slug: string, idToken: string): Promise<{ bool: boolean }> => {
```suggestion
    checkIfCanPromote: async (slug: string, idToken: string): Promise<boolean> => {
```
Er vel ganske unødvendig å returnere et objekt med et felt når typen bare er `boolean`? Man forstår returverdi av funksjonsnavnet.

2023-02-14 21:46 UTC, bakseter commented on frontend/src/components/registration-row.tsx
> +        const { bool } = await WaitinglistAPI.checkIfCanPromote(registration.slug, idToken);
```suggestion
        const bool = await WaitinglistAPI.checkIfCanPromote(registration.slug, idToken);
```

2023-02-15 06:48 UTC, omfj approved these changes

2023-02-15 06:48 UTC, omfj commented on backend/src/main/kotlin/no/uib/echo/routes/WaitinglistRoute.kt
> +            call.respond(HttpStatusCode.OK, "approved")
Kunne vi også ha litt mer beskrivende error-melding? Typ "bruker med eposten ble flyttet fra venteliste på arrg"?

2023-02-15 06:51 UTC, omfj requested changes

2023-02-15 06:51 UTC, omfj commented on frontend/src/lib/api/waitinglist.ts
> +            console.log('promoteDirectly');
Fjern console log?

2023-02-15 06:51 UTC, omfj commented on backend/src/main/kotlin/no/uib/echo/routes/WaitinglistRoute.kt
> +            call.respond(HttpStatusCode.OK, "approved")
Mente ikke å approve lol

2023-02-15 08:24 UTC, bakseter approved these changes

2023-02-15 08:46 UTC, omfj commented
Før merge. Kanskje endre på modalen som kommer når du prøver å slette en person fra arrg. Nå står det at neste person automatisk rykkes opp. @Epirius

2023-02-15 08:47 UTC, omfj commented
Ellers ser det veldig bra ut.

2023-02-15 09:40 UTC, omfj approved these changes

2023-02-15 10:21 UTC, Epirius commented
@omfj  kan du se på den?

2023-02-15 10:22 UTC, omfj commented
@Epirius se på hva?

2023-02-15 10:23 UTC, Epirius commented
@omfj merge conflict

2023-02-15 10:24 UTC, omfj commented
åja lol. seff.

2023-02-15 10:39 UTC, merged