Feature/prikkesystem
echo-webkom/echo-web pull request #957
Opened 2023-03-01 16:10 UTC by tkol02

Prikkesystem for bedkom! 
(Dette kan senere utvides til andre undergrupper, men for nå er bedkom prioritert).

La til en ny side på /dashboard/prikkesystem. Nå er dette bare en oversikt over alle brukere som har prikker, men man kan ikke endre antall prikker her enda.
![Screenshot 2023-03-01 at 14 33 51](https://user-images.githubusercontent.com/91483527/222195131-845e7cb3-c9ed-45a9-b5ce-cfe7f5a60a28.png)
Prikkesystemsiden ligger på /dashboard hos oss i Webkom, mens bedkom har en knapp direkte til /prikkeystem fra /profile

For å endre prikker må man slette påmelding under et bedriftarrangement (kan senere utvides til at man endrer på /dashboard/prikkesystem. 
<img width="1185" alt="Screenshot 2023-02-15 at 17 05 43" src="https://user-images.githubusercontent.com/91483527/222194747-ee307add-7f08-441e-940f-2abf924687c7.png">

På "min profil" vises det hvor mange prikker en bruker har, men viser ingenting om en ikke har noen prikker.
<img width="950" alt="Screenshot 2023-02-15 at 17 05 20" src="https://user-images.githubusercontent.com/91483527/222194676-892c5ee7-ad6a-44c9-90ad-b23ffbd1b091.png">

2023-03-02 10:11 UTC, boaanes commented on backend/src/main/kotlin/no/uib/echo/DatabaseHandler.kt
> +            dots = 0,
Kan vi kalle det `strikes` i stedet? overalt
```suggestion
            strikes = 0,
```

2023-03-02 12:11 UTC, boaanes commented on backend/src/main/kotlin/no/uib/echo/DatabaseHandler.kt
> +            strike = 0,
Veldig pirkete, jeg vet, men flertall gir mest mening IMO
```suggestion
            strikes = 0,
```

2023-03-02 12:16 UTC, tjekol commented on backend/src/main/kotlin/no/uib/echo/DatabaseHandler.kt
> +            strike = 0,
😭

2023-03-02 15:06 UTC, omfj requested changes

2023-03-02 15:06 UTC, omfj commented on backend/src/main/kotlin/no/uib/echo/routes/RegistrationRoutes.kt
> +import org.jetbrains.exposed.sql.*
Ikke lov med wildcard import!!

2023-03-02 15:06 UTC, omfj commented on frontend/src/pages/api/registration/index.ts
> +        if (req.method === 'DELETE') {
Denne kan flyttes inn i `UserAPI`, eller så kan du kanskje lage `StrikesAPI`.

2023-03-03 14:15 UTC, omfj commented on frontend/src/pages/api/registration/index.ts
> +        if (req.method === 'DELETE') {
Altså, det er bedre å gjøre disse requestene på client-side. Når du flytter kode under `/pages/api/`, så blir den koden kjørt på serveren.

2023-03-06 17:29 UTC, boaanes commented
To spørsmål:
- Bør ikke bedkom ha mulighet til å endre/resette antall prikker i dashboard?
- Dersom man har 5 prikker bør man vel ikke kunne melde seg på bedpreser? Slik det er nå får jeg meldt meg på med 5 prikker.

2023-03-07 12:40 UTC, bakseter commented on frontend/src/lib/api/user.ts
> +
Denne blir vel aldri brukt? Ser ut som meningen er å sende en `DELETE`-request, men det gjøres vel i `RegistrationAPI.deleteRegistration`? Her er også syntaks litt feil, du bruker syntax til Next.js API route, så denne hadde ikke funket i praksis.

2023-03-07 12:41 UTC, bakseter reviewed
Bare et lite spm

2023-03-08 11:18 UTC, tkol02 commented on frontend/src/lib/api/user.ts
> +
dette var denne som lå i `src/pages/api/registration/index.s` som ole mangnus ba meg flytta te userAPI, men heilt ærlig har eg mista hodet på koffer. men om den isje brukes kan eg bare fjerna den

2023-03-08 11:32 UTC, tkol02 commented
> To spørsmål:
> 
> * Bør ikke bedkom ha mulighet til å endre/resette antall prikker i dashboard?
> * Dersom man har 5 prikker bør man vel ikke kunne melde seg på bedpreser? Slik det er nå får jeg meldt meg på med 5 prikker.

Enig at det burde gå an. Det var litt det som var ideen med dashboardet, men akkurat nå er eneste måten å endre prikker på ved å slette en påmelding. Trenge såfall hjelp om eg ska få det te, eller om någen andre vil ta det så går det heilt fint åg.

Det at en har 5 prikker så sperre det påmelding for bedpress e vel fort gjort, kan se på det nå.

2023-03-08 12:26 UTC, bakseter commented on frontend/src/lib/api/user.ts
> +
Ja, du kan vel bare fjerne denne og teste at det funker etterpå.

2023-03-08 12:31 UTC, bakseter commented
Jeg synes det er greit å få merget dette snart uten så sykt mye mer endringer, så får Bedkom bare teste ut litt selv @boaanes? Kjøre litt MVP i starten, og så legge til features underveis. Er ikke akkurat kritisk infrastruktur dette.

2023-03-08 12:58 UTC, omfj commented
Enig med @bakseter

2023-03-08 14:59 UTC, boaanes commented
ja enig

2023-03-09 09:04 UTC, bakseter approved these changes

2023-03-09 09:42 UTC, boaanes commented
@omfj må også approve

2023-03-09 09:43 UTC, omfj approved these changes

2023-03-09 11:16 UTC, omfj commented
Ship it! 🛳️🚀

2023-03-09 11:39 UTC, bakseter commented on frontend/package.json
> +<<<<<<< HEAD
fjern

2023-03-09 11:39 UTC, bakseter commented on frontend/package.json
> +<<<<<<< HEAD
```suggestion
```

2023-03-09 11:39 UTC, bakseter commented on frontend/package.json
> +=======
```suggestion
```

2023-03-09 11:40 UTC, bakseter commented on frontend/package.json
> +>>>>>>> 631573f6 (⬆️ Update dependency zod to v3.21.0)
```suggestion
```

2023-03-09 11:40 UTC, bakseter commented on yarn.lock
> +<<<<<<< HEAD
```suggestion
```

2023-03-09 11:46 UTC, bakseter commented on yarn.lock
> +>>>>>>> 631573f6 (⬆️ Update dependency zod to v3.21.0)
bare fjern hele den her så burde alt være good
```suggestion
```

2023-03-09 11:50 UTC, bakseter approved these changes

2023-03-09 12:18 UTC, merged

2023-03-09 12:27 UTC, bakseter commented
Wooooops vi glemte helt å lage en database-migration for å legge til "strikes"-kolonnen @tkol02

2023-03-09 12:30 UTC, tkol02 commented
oh nooo