feat/upcoming events
echo-webkom/echo-web pull request #960
Opened 2023-03-01 17:04 UTC by bocianowski1

Viser kommende bedpresser (med to s'er) og arrangementer på profilen.

2023-03-02 09:56 UTC, boaanes requested changes, later dismissed
Bra jobba! Har egentlig kun litt pirk og komme med.

2023-03-02 09:56 UTC, boaanes commented on backend/src/main/kotlin/no/uib/echo/routes/RegistrationRoutes.kt
> +        call.respond(userRegistrations)
```suggestion
        call.respond(HttpStatusCode.OK, userRegistrations)
```

2023-03-02 09:56 UTC, boaanes commented on backend/src/main/kotlin/no/uib/echo/routes/RegistrationRoutes.kt
> +            call.respond(HttpStatusCode.Unauthorized)
```suggestion
            call.respond(HttpStatusCode.Forbidden)
```

2023-03-02 09:56 UTC, boaanes commented on frontend/src/components/profile-happening-preview.tsx
> +}
Kan bruker `event.happeningType` for å se om det er bedpres eller ikke.

```suggestion
interface Props {
    event: Happening;
}
```

2023-03-02 09:56 UTC, boaanes commented on frontend/src/components/profile-happening-preview.tsx
> +const ProfileHappeningPreview = ({ isBedpres, event }: Props) => {
```suggestion
const ProfileHappeningPreview = ({ event }: Props) => {
```

2023-03-02 09:56 UTC, boaanes commented on frontend/src/components/profile-happening-preview.tsx
> +            )}
Koden på de to forskjellige er jo veeeldig lik. Den kan nok kombineres ganske lett og heller skille på bedpres og arrangement kun der dere trenger det.

2023-03-02 09:56 UTC, boaanes commented on frontend/src/components/profile-info.tsx
> +                });
Personlig synes jeg det er best med en feilmelding der arrangementene skal vises, i stedet for en toast.

2023-03-02 09:56 UTC, boaanes commented on frontend/src/components/profile-info.tsx
> +                    });
Samme her

2023-03-02 09:56 UTC, boaanes commented on frontend/src/components/profile-info.tsx
> +        });
Her kan man kanskje lage en egen funksjon i `lib/util`. Også har `date-fns` funksjoner som `isBefore` og `isAfter` som er mer leselige enn krokodilletegn.

2023-03-02 09:56 UTC, boaanes commented on frontend/src/components/profile-info.tsx
> +                                    {isNorwegian ? 'Ingen kommende arrangementer :(' : 'No upcoming events :('}
```suggestion
                                    {isNorwegian ? 'Du er ikke påmeldt noen kommende arrangementer' : 'You are not registered for any upcoming events'}
```

2023-03-02 09:56 UTC, boaanes commented on frontend/src/components/profile-info.tsx
> +                                        : 'No upcoming bedpres :('}
samme her

2023-03-02 10:15 UTC, omfj requested changes, later dismissed

2023-03-02 10:15 UTC, omfj commented on backend/src/main/kotlin/no/uib/echo/routes/RegistrationRoutes.kt
> +    get("/user/registrations/{email?}") {
Denne trenger vel ikke å være optional?

2023-03-02 10:15 UTC, omfj commented on backend/src/main/kotlin/no/uib/echo/routes/RegistrationRoutes.kt
> +        }
```suggestion
        val userRegistrations = transaction {
            Registration.select {
                userEmail eq email
}.map {
            it[Registration.happeningSlug]
        }
```

Skriver på mobil, men kan ikke denne skrives litt lettere?

2023-03-02 12:39 UTC, bakseter commented on backend/src/main/kotlin/no/uib/echo/routes/RegistrationRoutes.kt
> +        }
var vel egt jeg som satte dere på feil spor her en gang way back, sry :))

2023-03-02 12:47 UTC, bocianowski1 commented on frontend/src/components/profile-happening-preview.tsx
> +const ProfileHappeningPreview = ({ isBedpres, event }: Props) => {
oki nice takk

2023-03-03 11:06 UTC, omfj commented on backend/src/main/kotlin/no/uib/echo/routes/RegistrationRoutes.kt
> +    get("/user/registrations/{email?}") {
Jeg tror også `/user/{email}/registrations` hadde vært et bedre endepunkt.

2023-03-03 11:18 UTC, bakseter commented on backend/src/main/kotlin/no/uib/echo/routes/RegistrationRoutes.kt
> +        call.respond(userRegistrations)
@boaanes Om man ikke gir noe statuskode så er `HttpStatusCode.OK` default, så trengs egt ikke. Med mindre du tenkte på leselighet.

2023-03-03 12:09 UTC, bocianowski1 reviewed
fiksa

2023-03-03 12:23 UTC, boaanes commented on backend/src/main/kotlin/no/uib/echo/routes/RegistrationRoutes.kt
> +        call.respond(userRegistrations)
Tenkte på leselighet og consistency ja @bakseter

2023-03-03 13:46 UTC, bocianowski1 commented on frontend/src/components/profile-info.tsx
> +        });
tenker du liksom: 
if isAfter(a, b) return 1;
else if isBefore(a, b) return -1;
else return 0;
?

2023-03-03 14:14 UTC, boaanes commented on frontend/src/components/profile-info.tsx
> +        });
ja @bocianowski1

2023-03-06 21:08 UTC, omfj commented on frontend/src/components/profile-info.tsx
> +        });
Er denne resolved? @bocianowski1

2023-03-07 12:40 UTC, omfj approved these changes

2023-03-07 12:59 UTC, omfj commented on frontend/src/components/profile-info.tsx
> +        });
Fikset nå.

2023-03-07 14:55 UTC, bakseter commented
![2023-03-07_15:53:31](https://user-images.githubusercontent.com/6720179/223458617-33b15a11-ef70-4931-aa6e-3f619bfa50f8.png)

:thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: 

Skulle stått Bouvet der

2023-03-08 12:24 UTC, omfj commented
@bakseter Jeg skal se på det.

2023-03-14 18:39 UTC, bocianowski1 commented
@bakseter hva syns du nå? @omfj mente det var noe fakka med backend preview, kunne du sett på det?

2023-03-14 20:06 UTC, omfj commented
Preview er litt rar, men tror det skal gå greit å merge?

2023-03-14 20:08 UTC, bakseter commented
@omfj jeg skal ha fikset preview, jeg får en error fra Sanity, se link:
https://pgq2pd26.apicdn.sanity.io/v2021-04-10/data/query/production?query=%20*[_type%20==%20%22happening%22%20&&%20slug.current%20in%20$slugs%20&&%20!(_id%20in%20path(%27drafts.**%27))]%20|%20order(date%20asc)%20{%20title,%20%22slug%22:%20slug.current,%20date,%20registrationDate,%20registrationDeadline,%20studentGroupRegistrationDate,%20studentGroups,%20onlyForStudentGroups,%20body,%20deductiblePayment,%20location,%20locationLink,%20companyLink,%20happeningType,%20contactEmail,%20additionalQuestions[]%20-%3E%20{%20questionText,%20inputType,%20alternatives%20},%20%22logoUrl%22:%20logo.asset%20-%3E%20url,%20studentGroupName,%20_createdAt,%20spotRanges[]%20-%3E%20{%20minDegreeYear,%20maxDegreeYear,%20spots%20}%20}%20&$slugs=[%22kantega%22]

2023-03-14 20:11 UTC, bakseter commented
Det er URL'en fra en request i frontend som failer

![2023-03-14_21:11:22](https://user-images.githubusercontent.com/6720179/225125197-07eb4575-5cb9-41fb-a11b-80f3cb75cf37.png)

2023-03-14 20:13 UTC, omfj commented
Hvorfor får jeg den ikke på dev?

2023-03-14 20:14 UTC, omfj commented
CORS?

2023-03-14 20:17 UTC, bakseter commented
Om du trykker på linken så ser det ut som om Sanity-query er feil elns: `Unknown query parameters: " slug.current in $slugs "`

2023-03-14 20:20 UTC, omfj commented
Ja, men det sa litt lite. Veldig sikker på at det ikke ugyldig syntax. https://www.sanity.io/docs/query-cheat-sheet#3949cadc7524

2023-03-14 20:23 UTC, oyvindgrutle commented
Eg har fiksa det tidligare med ` slug.current in ${JSON.stringify(slugs)} `

2023-03-14 20:25 UTC, omfj commented
Får prøve det igjen da.

2023-03-14 20:25 UTC, oyvindgrutle commented
> Ja, men det sa litt lite. Veldig sikker på at det ikke ugyldig syntax. https://www.sanity.io/docs/query-cheat-sheet#3949cadc7524

Med `  slug.current in $slugs ` blir [] fjerna som blir ugyldig syntax

2023-03-14 20:29 UTC, omfj commented
@oyvindgrutle Så sanity gjør det til `...&& slug.current in  && !(_id in path('drafts.**'))]...`?

2023-03-14 20:32 UTC, oyvindgrutle commented
@omfj hvis slugs e for eksempel ` [bekk, knowit] ` blir det ` slug.current in bekk, knowit !(_id in path('drafts.**'))]...  ` hvis eg huske rett.

2023-03-14 20:33 UTC, omfj commented
Rart. Jeg kopierte queryen fra URL i Sanity Vision og der får jeg ikke problemer.
![image](https://user-images.githubusercontent.com/32321558/225129822-3c1a4606-4308-4733-8631-17da8ac73961.png)

2023-03-14 20:38 UTC, omfj commented
Og det funker jo om man kjører lokalt?

2023-03-14 21:04 UTC, bakseter commented
Ser ut BACKEND_URL peker på feil backend på nyeste commit, men får fortsatt feil med URL til Sanity

2023-03-14 21:05 UTC, omfj commented
Om jeg enabler CORS på de URLene så får jeg feil i backend om at den ikke finner brukeren sine påmeldinger. Altså 404 response.

2023-03-14 21:08 UTC, bakseter commented
Ja pga nyeste Vercel preview peker på dev backend og ikke backend preview, men fortsatt

2023-03-14 21:10 UTC, bakseter commented
Åja nå gir Sanity query 200 OK så burde være good da

2023-03-14 21:12 UTC, omfj commented
@bakseter Så det var CORS?

2023-03-14 21:13 UTC, bakseter commented
Tror det var det Øyvind sa?

2023-03-14 21:15 UTC, omfj commented
Hva faen

2023-03-14 21:19 UTC, omfj commented
Merge da?

2023-03-14 21:32 UTC, merged

2023-03-15 09:55 UTC, oyvindgrutle commented
![image](https://user-images.githubusercontent.com/32832996/225273561-5a9f0d89-3b37-4adc-8f74-fc5e6fa9d8f6.png)

2023-03-15 10:07 UTC, omfj commented
Hahaha. GG.

2023-03-15 10:11 UTC, omfj commented
Sjekk på nytt @oyvindgrutle. Jeg la til echo.uib.no i CORS.

2023-03-15 10:13 UTC, omfj commented
Funker til meg nå.

2023-03-15 10:13 UTC, oyvindgrutle commented
Funke nå ja👍

2023-03-15 10:32 UTC, bakseter commented
wtf hvorfor trengte vi plutselig CORS :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking:

2023-03-15 10:33 UTC, bakseter commented
ååå dette er vel første gang vi kjører Sanity-queries i frontend fra client? sjukt

2023-03-15 11:39 UTC, omfj commented
@bakseter Ja det jeg og tror.

2023-03-15 11:39 UTC, omfj commented
@bakseter Vi kan faktisk hente de i `getServerSideProps` om vi vil og da